const defaultChosenData = {
  businessSphereIndex: -1,
  size: {
    board: {
      x: -1,
      y: -1,
    },
    icon: {
      x: -1,
      y: -1,
    },
  },
  title: '',
  titleFont: '',
  tagline: '',
  taglineFont: '',
  mainColor: '',
  titleColor: '',
  icon: '',
  technology: '',
  technologyIndex: -1,
  boardUrl: '',
  customer: {
    name: '',
    phone: '',
    city: '',
    needsHelp: false,
  },
  optimalLetters: {
    title: {
      x: -1,
      y: -1,
      price: [],
    },
    tagline: {
      x: -1,
      y: -1,
      price: -1,
    },
  },
  price: -1,
};

const initialData = {
  businessSphereList: [
    {
      title: 'Магазин / Киоск',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'Кафе / Бар / Фастфуд',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'Авто / Мойка / СТО',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'Аптека / Оптика',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'Стоматология / Медицина',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'ЗОО товары / ВетКлиника',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'Нотариус / Обмен валют',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
    {
      title: 'Другое',
      icons: [
        'icons/1.svg',
        'icons/2.svg',
        'icons/3.svg',
        'icons/4.svg',
        'icons/5.svg',
        'icons/6.svg',
        'icons/7.svg',
        'icons/8.svg',
        'icons/9.svg',
        'icons/10.svg',
        'icons/11.svg',
        'icons/12.svg',
        'icons/13.svg',
        'icons/14.svg',
        'icons/15.svg',
      ],
      examples: [
        'technologies/1.jpg',
        'technologies/2.jpg',
        'technologies/3.jpg',
        'technologies/4.jpg',
      ],
    },
  ],
  sizes: {
    boards: [
      {
        self: {
          x: 5295,
          y: 900,
        },
        icon: {
          x: 800,
          y: 800,
        },
      },
      {
        self: {
          x: 3528,
          y: 900,
        },
        icon: {
          x: 800,
          y: 800,
        },
      },
      {
        self: {
          x: 1764,
          y: 900,
        },
        icon: {
          x: 800,
          y: 800,
        },
      },
      {
        self: {
          x: 1764,
          y: 900,
        },
        icon: {
          x: 450,
          y: 450,
        },
      },
      {
        self: {
          x: 2698,
          y: 900,
        },
        icon: {
          x: 800,
          y: 800,
        },
      },
      {
        self: {
          x: 5295,
          y: 523,
        },
        icon: {
          x: 400,
          y: 400,
        },
      },
      {
        self: {
          x: 3528,
          y: 523,
        },
        icon: {
          x: 400,
          y: 400,
        },
      },
      {
        self: {
          x: 1764,
          y: 523,
        },
        icon: {
          x: 400,
          y: 400,
        },
      },
      {
        self: {
          x: 2698,
          y: 523,
        },
        icon: {
          x: 400,
          y: 400,
        },
      },
      {
        self: {
          x: 1298,
          y: 523,
        },
        icon: {
          x: 300,
          y: 300,
        },
      },
    ],
    letters: {
      title: [
        {
          x: 420,
          y: 450,
          price: [
            1653,
            431,
            1356,
            1693,
          ],
        },
        {
          x: 410.9,
          y: 440,
          price: [
            1648,
            455,
            1442,
            1752,
          ],
        },
        {
          x: 411.25,
          y: 400,
          price: [
            1700,
            479,
            1731,
            1758,
          ],
        },
        {
          x: 280,
          y: 300,
          price: [
            1176.5,
            284.17,
            904.7,
            1012.7,
          ],
        },
        {
          x: 233.13,
          y: 250,
          price: [
            1013.5,
            241.5,
            786.75,
            669.75,
          ],
        },
        {
          x: 186.37,
          y: 200,
          price: [
            825,
            186,
            639.5,
            486,
          ],
        },
        {
          x: 140,
          y: 150,
          price: [
            725.67,
            169.34,
            551,
            383.67,
          ],
        },
      ],
      tagline: [
        {
          x: 135,
          y: 150,
          price: 59,
        },
        {
          x: 90,
          y: 100,
          price: 38,
        },
        {
          x: 58,
          y: 65,
          price: 30,
        },
      ],
    },
  },
  colors: {
    title: [
      'pink',
      'red',
      'orange',
      'yellow',
      'green',
      'blue',
      'brown',
    ],
    main: [
      'pink',
      'red',
      'orange',
      'yellow',
      'green',
      'blue',
      'brown',
    ],
  },
  fonts: [
    'OldStandardTT',
    'RobotoMono',
    'Ruda',
  ],
  technologies: [
    'Technology 1',
    'Technology 2',
    'Technology 3',
    'Technology 4',
  ],
  defaultUtm: {
    source:   'default_source',
    medium:   'default_medium',
    campaign: 'default_campaign',
    term:     'default_term',
    content:  'default_content',
  },
};
